import slugify from '../utils/slugify'

export default {
  title: "Events / Workshops",
  name: 'events',
  type: "document",
  fields: [
    {
      title: "Title",
      description: "The name of this news article",
      name: "title",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Intro Text",
      description: "The short text intro that appears in the hero",
      name: "introText",
      type: 'text',
      rows: 3,
      validation: Rule => Rule.required()
    },
    {
      title: "Hero Image",
      description: "The image that will appear in the hero and the teaser for this article",
      name: "heroImage",
      type: "image",
      validation: Rule => Rule.required()
    },
    {
      title: "Event / Workshop Date",
      description: "The date this event or workshop will be taking place, press the button to the right to pick a date.",
      name: "date",
      type: "date",
      options: {
        dateFormat: "MMMM Do YYYY",
      }
    },
    {
      title: "Event / Workshop Time",
      description: "The time this event or workshop will be taking place.",
      name: "time",
      type: "string"
    },
    {
      title: "Event / Workshop Location",
      description: "The location this event or workshop will be taking place.",
      name: "location",
      type: "string"
    },
    {
      title: 'Content',
      description: "The main content area, use the + button top right to add component blocks",
      name: 'content',
      type: 'blockContentGuides',
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      description: 'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: 'title',
        maxLength: 96,
        slugify: title => slugify(title)
      },
      validation: Rule => Rule.required()
    },
    {
      title: 'SEO / Share Settings',
      name: 'seo',
      type: 'seo'
    }
  ],
  preview: {
    select: {
      title: 'title'
    },
    prepare ({ title }) {
      return {
        title
      }
    }
  }
}