import slugify from '../utils/slugify'

export default {
  title: "News",
  name: 'news',
  type: "document",
  fields: [
    {
      title: "Title",
      description: "The name of this news article",
      name: "title",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Intro Text",
      description: "The short text intro that appears in the hero",
      name: "introText",
      type: 'text',
      rows: 3,
      validation: Rule => Rule.required()
    },
    {
      title: "Hero Image",
      description: "The image that will appear in the hero and the teaser for this article",
      name: "heroImage",
      type: "image",
      validation: Rule => Rule.required()
    },
    {
      title: 'Content',
      description: "The main content area, use the + button top right to add component blocks",
      name: 'content',
      type: 'blockContentExtended',
    },
    {
      title: 'Categories',
      name: 'categories',
      description: 'The categories for this article',
      type: 'array',
      of: [
        {
          type: 'reference',
          to: [
            {type: 'newsCategory'}
          ]
        }
      ],
    },
    {
      title: 'Author',
      name: 'author',
      description: 'The author of this article',
      type: 'reference',
      to: [
        {type: 'team'},
        {type: 'author'}
      ],
      validation: Rule => Rule.required()
    },
    {
      title: "Post Date",
      description: "The date this article was posted, press the button to the right to pick a date.",
      name: "date",
      type: "date",
      options: {
        dateFormat: "MMMM Do YYYY",
      },
      validation: Rule => Rule.required()
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      description: 'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: 'title',
        maxLength: 96,
        slugify: title => slugify(title)
      },
      validation: Rule => Rule.required()
    },
    {
      title: 'SEO / Share Settings',
      name: 'seo',
      type: 'seo'
    }
  ],
  preview: {
    select: {
      title: 'title'
    },
    prepare ({ title }) {
      return {
        title
      }
    }
  }
}