import slugify from '../utils/slugify'

export default {
  title: "Services",
  name: 'service',
  type: "document",
  fields: [
    {
      title: "Title",
      description: "The name of this service, eg: 'Content Strategy'",
      name: "title",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Images",
      description: 'The gallery of images for this service, the first image will be used as the teaser image',
      name: 'images',
      type: 'array',
      options: {
        layout: 'grid'
      },
      of: [{
        type: 'image'
      }],
      validation: Rule => Rule.min(1)
    },
    {
      title: "Icon",
      description: 'The icon that supports this service',
      name: 'icon',
      type: 'image',
    },
    {
      title: 'Content',
      name: 'content',
      type: 'array', 
      of: [{type: 'block'}],
      description: 'The content for this service which will appear in the expanded accordion',
      validation: Rule => Rule.required()
    },
    {
      title: "Clients",
      description: 'The clients associated with this service.',
      name: 'clients',
      type: 'array',
      of: [{
        title: 'Client / Case Study',
        name: 'client',
        type: 'reference',
        to: [{type: 'caseStudy'}]
      }]
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      description: 'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: 'title',
        maxLength: 96,
        slugify: title => slugify(title)
      },
      validation: Rule => Rule.required()
    },
    {
      title: 'SEO / Share Settings',
      name: 'seo',
      type: 'seo'
    },
    {
      name: "order",
      title: "Order",
      type: "number",
      hidden: true,
    }
  ]
}